name: Build Firmware

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main, ci ]
  workflow_dispatch: # Allows you to trigger this build manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32s2
        path: ''

