name: Build Firmware

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main, ci ]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [esp32s2, esp32s3, esp32] 

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v6.0.2
        target: ${{ matrix.target }}
        path: ''
        
    - name: Zip up bins
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.target }}
        path: |
          build/*.bin
          build/bootloader/*.bin
          build/partition_table/*.bin

  release-bins:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' 
    permissions:
      contents: write
    steps:
      - name: Download all built bins
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: artifacts/*.bin
